# -*- coding: utf-8 -*-
"""39 EjerciciosPython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GltzkThQTiBNr3NRjw4FQ4uJ2_qJhtrl
"""

#1. Calcular el área de un triángulo con base y altura dadas.

# Zona dela base y la altura
def tomar_datos():
    base = int(input("Escribe la base del triángulo: "))
    altura = int(input("Escribe la altura del triángulo: "))
    return base, altura

# se calcula el area
def calcular_area(base, altura):
    area = (base * altura) / 2
    return area

# mostrar resultado
def mostrar_resultado(area):
    print("El área del triángulo es:", area)

# Zona principal
b, a = tomar_datos()
resultado = calcular_area(b, a)
mostrar_resultado(resultado)

#2. Determinar el volumen de una esfera con su radio dado.

# Zona de la radio
def tomar_radio():
  print("Escriba el radio de la esfera")
  radio=int(input())
  return radio

# se calcula el resultado
def calcular_resultado(radio):
  resultado=(4/3)* 3.1416 * radio**3
  return resultado

# mostrar resultado
def mostrar_resultado(dato_resultado):
  print("el volumen de la esfera es:",dato_resultado)

# Zona principal
radio=tomar_radio()
dato_resultado=calcular_resultado(radio)
mostrar_resultado(dato_resultado)

#3. Calcular el área de un rectángulo con longitud y ancho dados.

# Función que toma la longitud y el ancho
def tomar_datos():
    longitud = float(input("Escribe la longitud del rectángulo: "))
    ancho = float(input("Escribe el ancho del rectángulo: "))
    return longitud, ancho

# Función para calcular el área
def calcular_area(longitud, altura):
    area = longitud * altura
    return area

# Función para mostrar el resultado
def mostrar_resultado(area):
    print("El área del rectángulo es:", area)

# Zona principal
l, a = tomar_datos()
resultado = calcular_area(l, a)
mostrar_resultado(resultado)

#4. Determinar el volumen de un cilindro con radio de la base y altura especificados


# Función que toma el radio y la altura
def tomar_datos():
    radio = float(input("Escribe el radio de la base: "))
    altura = float(input("Escribe la altura del cilindro: "))
    return radio, altura

# Función para calcular el volumen
def calcular_volumen(radio, altura):
    volumen = 3.14 * (radio ** 2) * altura
    return volumen

# Función para mostrar el resultado
def mostrar_resultado(volumen):
    print("El volumen del cilindro es:", volumen)

# Zona principal
r, a = tomar_datos()
resultado = calcular_volumen(r, a)
mostrar_resultado(resultado)

#5. Calcular el área de un círculo con su radio dado

def area_circulo():
  print("Escriba el radio del circulo")
  radio_circulo=int (input())
  return radio_circulo

def procesar_resultado(radio):
  resultado= 3.1416 * radio**2
  return resultado

def imprimir_resultado(mostrar_resultado):
  print("el area del circulo es: ", mostrar_resultado)

radio = area_circulo()
mostrar_resultado = procesar_resultado(radio)
imprimir_resultado(mostrar_resultado)

#6. Determinar el volumen de un cono con radio de la base y altura especificados

def volumen_cono():
  radio_cono=int(input("Ingrese el radio del cono: "))
  altura_cono=int(input("Ingrese altura del cono: "))
  return radio_cono,altura_cono

def procesar_resultado(radio,altura):
  resultado= (1/3) * 3.1416 * radio**2 * altura
  return resultado

def imprimir_resultado(mostrar_resultado):
  print("el volumen del cono es:", mostrar_resultado)

radio,altura = volumen_cono()
mostrar_resultado=procesar_resultado(radio,altura)
imprimir_resultado(mostrar_resultado)

#7. Convertir grados Celsius a grados Fahrenheit

# Función para tomar la temperatura en Celsius
def tomar_datos():
    celsius = float(input("Introduce la temperatura en grados Celsius: "))
    return celsius

# Función para calcular los grados Fahrenheit
def calcular_temperatura(celsius):
    fahrenheit = (celsius * 9/5) + 32
    return fahrenheit

# Función para mostrar el resultado
def mostrar_resultado(fahrenheit):
    print("La temperatura en grados Fahrenheit es:", fahrenheit)

# Zona principal
c = tomar_datos()
resultado = calcular_temperatura(c)
mostrar_resultado(resultado)

#8. Convertir dólares a euros utilizando una tasa de cambio dada

# Función para tomar los datos (dólares y tasa de cambio)
def tomar_datos():
    dolares = float(input("Introduce la cantidad en dólares: "))
    tasa_cambio = float(input("Introduce la tasa de cambio (1 USD = 0.85 EUR): "))
    return dolares, tasa_cambio

# Función para calcular los euros
def calcular_euros(dolares, tasa_cambio):
    euros = dolares * tasa_cambio
    return euros

# Función para mostrar el resultado
def mostrar_resultado(euros):
    print(f"La cantidad en euros es: {euros:.2f}€")

# Zona principal
d, tc = tomar_datos()
resultado = calcular_euros(d, tc)
mostrar_resultado(resultado)

#9. Calcular el área de un trapecio con sus longitudes de bases y altura especificadas.

# Función para tomar las longitudes de las bases y la altura
def tomar_datos():
    base_mayor = float(input("Introduce la longitud de la base mayor del trapecio: "))
    base_menor = float(input("Introduce la longitud de la base menor del trapecio: "))
    altura = float(input("Introduce la altura del trapecio: "))
    return base_mayor, base_menor, altura

# Función para calcular el área del trapecio
def calcular_area(base_mayor, base_menor, altura):
    area = (base_mayor + base_menor) / 2 * altura
    return area

# Función para mostrar el resultado
def mostrar_resultado(area):
    print("El área del trapecio es:", area)

# Zona principal
b_mayor, b_menor, a = tomar_datos()
resultado = calcular_area(b_mayor, b_menor, a)
mostrar_resultado(resultado)

#10. Determinar el volumen de un prisma rectangular con longitud, ancho y altura especificados.

# Función para tomar las dimensiones del prisma
def tomar_datos():
    longitud = float(input("Introduce la longitud del prisma rectangular: "))
    ancho = float(input("Introduce el ancho del prisma rectangular: "))
    altura = float(input("Introduce la altura del prisma rectangular: "))
    return longitud, ancho, altura

# Función para calcular el volumen
def calcular_volumen(longitud, ancho, altura):
    volumen = longitud * ancho * altura
    return volumen

# Función para mostrar el resultado
def mostrar_resultado(volumen):
    print("El volumen del prisma rectangular es: ",volumen)

# Zona principal
l, a, al = tomar_datos()
resultado = calcular_volumen(l, a, al)
mostrar_resultado(resultado)

#11. Convertir kilómetros a millas.

# Función para tomar los kilómetros
def tomar_datos():
    kilometros = float(input("Introduce la distancia en kilómetros: "))
    return kilometros

# conversión a millas (1 km = 0.621371 millas)
def calcular_conversion(kilometros):
    millas = kilometros * 0.621371
    return millas

# Función para mostrar el resultado
def mostrar_resultado(millas):
    print("La distancia en millas es:",millas)

# Zona principal
k = tomar_datos()
resultado = calcular_conversion(k)
mostrar_resultado(resultado)

#12. Calcular el área de un cuadrado con el lado dado.

# Función para tomar el lado del cuadrado
def tomar_datos():
    lado = float(input("Introduce la longitud del lado del cuadrado: "))
    return lado

# Función para calcular el área del cuadrado
def calcular_area(lado):
    area = lado ** 2
    return area

# Función para mostrar el resultado
def mostrar_resultado(area):
    print("El área del cuadrado es: ", area)

# Zona principal
lado_cuadrado = tomar_datos()
resultado = calcular_area(lado_cuadrado)
mostrar_resultado(resultado)

#13. Determinar el volumen de una pirámide con longitud de la base, ancho de la base y altura especificados.

# Función para tomar las dimensiones de la pirámide
def tomar_datos():
    longitud_base = float(input("Introduce la longitud de la base de la pirámide: "))
    ancho_base = float(input("Introduce el ancho de la base de la pirámide: "))
    altura = float(input("Introduce la altura de la pirámide: "))
    return longitud_base, ancho_base, altura

# Función para calcular el volumen
def calcular_volumen(longitud_base, ancho_base, altura):
    volumen = (1/3) * longitud_base * ancho_base * altura
    return volumen

# Función para mostrar el resultado
def mostrar_resultado(volumen):
    print("El volumen de la pirámide es: ", volumen)

# Zona principal
l_base, a_base, a = tomar_datos()
resultado = calcular_volumen(l_base, a_base, a)
mostrar_resultado(resultado)

#14. Convertir pulgadas a centímetros.

# Función para tomar las pulgadas
def tomar_datos():
    pulgadas = float(input("Introduce la longitud en pulgadas: "))
    return pulgadas

# Función para calcular la conversión a centímetros (1 pulgada = 2.54 cm)
def calcular_conversion(pulgadas):
    centimetros = pulgadas * 2.54
    return centimetros

# Función para mostrar el resultado
def mostrar_resultado(centimetros):
    print("La longitud en centímetros es: ", centimetros)

# Zona principal
p = tomar_datos()
resultado = calcular_conversion(p)
mostrar_resultado(resultado)

#15. Calcular el área de un paralelogramo con base y altura dadas.

# Función para tomar los datos de la base y la altura
def tomar_datos():
    base = float(input("Escriba la base del paralelogramo: "))
    altura = float(input("Escriba la altura del paralelogramo: "))
    return base, altura

# Función para calcular el área del paralelogramo
def calcular_area(base, altura):
    area = base * altura
    return area

# Función para mostrar el resultado
def mostrar_resultado(area):
    print("El área del paralelogramo es: ", area)

# Zona principal
b, a = tomar_datos()
resultado = calcular_area(b, a)
mostrar_resultado(resultado)

#16. Determinar el volumen de un cubo con la longitud de un lado especificada.

# Función para tomar la longitud del lado
def tomar_datos():
    lado = float(input("Escribe la longitud del lado del cubo: "))
    return lado

# Función para calcular el volumen
def calcular_volumen(lado):
    volumen = lado ** 3
    return volumen

# Función para mostrar el resultado
def mostrar_resultado(volumen):
    print("El volumen del cubo es: ", volumen)

# Zona principal
lado_cubo = tomar_datos()
resultado = calcular_volumen(lado_cubo)
mostrar_resultado(resultado)

#17. Convertir libras a kilogramos.

# Función para tomar las libras
def tomar_datos():
    libras = float(input("Escribe la cantidad de libras: "))
    return libras

# Función conversión a kilogramos (1 libra = 0.453592 kilogramos)
def calcular_conversion(libras):
    kilogramos = libras * 0.453592
    return kilogramos

# Función para mostrar el resultado
def mostrar_resultado(kilogramos):
    print("La cantidad en kilogramos es: ", kilogramos)

# Zona principal
l = tomar_datos()
resultado = calcular_conversion(l)
mostrar_resultado(resultado)

#18. Calcular el área de un hexágono regular con su lado dado.

# Función para tomar el lado del hexágono
def tomar_datos():
    lado = float(input("Introduce la longitud del lado del hexágono: "))
    return lado

# Función para calcular el área del hexágono
def calcular_area(lado):
    area = (3 * (3 ** 0.5) * (lado ** 2)) / 2
    return area

# Función para mostrar el resultado
def mostrar_resultado(area):
    print("El área del hexágono regular es: ", area)

# Zona principal
lado_hexagono = tomar_datos()
resultado = calcular_area(lado_hexagono)
mostrar_resultado(resultado)

#19. Determinar el volumen de un prisma triangular con la longitud de la base, altura y ancho especificados.

# Función para tomar las dimensiones del prisma triangular
def tomar_datos():
    base_triangulo = float(input("Escriba la longitud de la base del triángulo: "))
    altura_triangulo = float(input("Escriba la altura del triángulo: "))
    longitud_prisma = float(input("Escriba la longitud del prisma: "))
    return base_triangulo, altura_triangulo, longitud_prisma

# Función para calcular el volumen
def calcular_volumen(base_triangulo, altura_triangulo, longitud_prisma):
    volumen = (0.5 * base_triangulo * altura_triangulo) * longitud_prisma
    return volumen

# Función para mostrar el resultado
def mostrar_resultado(volumen):
    print("El volumen del prisma triangular es: ", volumen)

# Zona principal
b_triangulo, a_triangulo, l_prisma = tomar_datos()
resultado = calcular_volumen(b_triangulo, a_triangulo, l_prisma)
mostrar_resultado(resultado)

#20. Convertir litros a galones.

# Función para tomar los litros
def tomar_datos():
    litros = float(input("Escriba los litros: "))
    return litros

# Función para calcular la conversión a galones
def calcular_conversion(litros):
    galones = litros * 0.264172
    return galones

# Función para mostrar el resultado
def mostrar_resultado(galones):
    print("La cantidad en galones es: " , galones)

# Zona principal
l = tomar_datos()
resultado = calcular_conversion(l)
mostrar_resultado(resultado)

#21. Escribe un programa que solicite dos números al usuario y muestre la suma de ambos.


# Función para tomar los dos números
def tomar_datos():
    numero1 = int(input("escriba el primer número: "))
    numero2 = int(input("escriba el segundo número: "))
    return numero1, numero2

# Función para calcular la suma
def calcular_suma(numero1, numero2):
    suma = numero1 + numero2
    return suma

# Función para mostrar el resultado
def mostrar_resultado(suma):
    print("La suma de los dos números es: ", suma)

# Zona principal
n1, n2 = tomar_datos()
resultado = calcular_suma(n1, n2)
mostrar_resultado(resultado)

#22. Crea un algoritmo que pida al usuario dos números y calcule la resta del primero menos el segundo.

# Función para tomar los dos números
def tomar_datos():
    num1 = int(input("Escribe el primer número: "))
    num2 = int(input("Escribe el segundo número: "))
    return num1, num2

# Función para calcular la resta
def calcular_resta(num1, num2):
    resta = num1 - num2
    return resta

# Función para mostrar el resultado
def mostrar_resultado(resta):
    print("La resta de los dos números es: ",resta)

# Zona principal
n1, n2 = tomar_datos()
resultado = calcular_resta(n1, n2)
mostrar_resultado(resultado)

#23. Desarrolla un programa que requiera dos números y muestre el producto de dichos valores.

# Función para tomar los dos números
def tomar_datos():
    num1 = int(input("Escriba el primer número: "))
    num2 = int(input("Escriba el segundo número: "))
    return num1, num2

# Función para calcular el producto
def calcular_producto(num1, num2):
    producto = num1 * num2
    return producto

# Función para mostrar el resultado
def mostrar_resultado(producto):
    print("El producto de los dos números es:", producto)

# Zona principal
n1, n2 = tomar_datos()
resultado = calcular_producto(n1, n2)
mostrar_resultado(resultado)

#24. Diseña un algoritmo que pida un número y calcule su cuadrado utilizando el operador de multiplicación.


# Función para tomar el número
def tomar_datos():
    numero = int(input("Introduce un número para calcular su cuadrado: "))
    return numero

# Función para calcular el cuadrado
def calcular_cuadrado(numero):
    cuadrado = numero * numero
    return cuadrado

# Función para mostrar el resultado
def mostrar_resultado(cuadrado):
    print("El cuadrado del número es: ", cuadrado)

# Zona principal
n = tomar_datos()
resultado = calcular_cuadrado(n)
mostrar_resultado(resultado)

#25. Escribe un programa que solicite dos números y calcule la división del primero entre el segundo.

# 1. Zona de entrada
def tomar_dividendo():
    n1 = float(input("Escribe el primer numero: "))
    return n1

# 2. Zona de entrada
def tomar_divisor():
    n2 = float(input("Escribe el segundo numero: "))
    return n2

# 3. Zona de procesamiento
def calcular_division(n1, n2):
    resul = n1 / n2
    return resul

# 4. Zona de salida
def mostrar_resultado(total):
    print("El resultado de la división es:" ,total)

# ZONA PRINCIPAL
num1 = tomar_dividendo()
num2 = tomar_divisor()
resultado_final = calcular_division(num1, num2)
mostrar_resultado(resultado_final)

#26. Crea un algoritmo que determine el residuo de la división entre dos números ingresados por el


# 1. Zona de entrada
def tomar_dividendo():
    n1 = float(input("Escribe el dividendo: "))
    return n1

# 2. Zona de entrada
def tomar_divisor():
    n2 = float(input("Escribe el divisor: "))
    return n2

# 3. Zona de procesamiento
def calcular_residuo(n1, n2):
    resul = n1 % n2
    return resul

# 4. Zona de salida
def mostrar_resultado(total):
    print("El residuo es:" ,total)

# ZONA PRINCIPAL
num1 = tomar_dividendo()
num2 = tomar_divisor()
resultado_final = calcular_residuo(num1, num2)
mostrar_resultado(resultado_final)

#27. Desarrolla un programa que pida un número y calcule su raíz cuadrada utilizando operadores aritméticos

# 1. Zona de entrada
def tomar_numero():
    n = float(input("Escribe el numero para calcular su raíz cuadrada: "))
    return n

# 2. Zona de procesamiento
def calcular_raiz(numero):
    raiz = numero ** 0.5
    return raiz

# 3. Zona de salida
def mostrar_resultado(valor_final):
    print("La raíz cuadrada es:", valor_final)

# ZONA PRINCIPAL
numero_base = tomar_numero()
resultado = calcular_raiz(numero_base)
mostrar_resultado(resultado)

#28. Diseña un algoritmo que solicite la base y la altura de un triángulo y calcule su área

# 1. Zona de entrada
def tomar_base():
    base = float(input("Escribe la base del triangulo: "))
    return base

# 2. Zona de entrada
def tomar_altura():
    altura = float(input("Escribe la altura del triangulo: "))
    return altura

# 3. Zona de procesamiento
def calcular_area_triangulo(b, al):
    area = (b * al) / 2
    return area

# 4. Zona de salida
def mostrar_resultado(valor_area):
    print("El área del triángulo es:",valor_area)

# ZONA PRINCIPAL
base_t = tomar_base()
altura_t = tomar_altura()
resultado = calcular_area_triangulo(base_t, altura_t)
mostrar_resultado(resultado)

#29. Escribe un programa que pida un número y determine si es par o impar usando el operador de módulo (%).

# 1. Zona de entrada
def tomar_numero():
    n = int(input("Escriba un numero: "))
    return n

# 2. Zona de procesamiento
def calcular_residuo(numero):
    res=numero % 2
    return res

# 3. Zona de salida
def mostrar_paroimpar(residuo):
    if residuo == 0:
        print("Es par.")
    else:
        print("Es impar.")

# ZONA PRINCIPAL
num = tomar_numero()
resultado = calcular_residuo(num)
mostrar_paroimpar(resultado)

#30.Crea un algoritmo que solicite el radio de un círculo y calcule su circunferencia.

# 1. Zona de entrada
def tomar_radio():
    r = float(input("Escribe el radio del circulo: "))
    return r

# 2. Zona de procesamiento
def calcular_circunferencia(radio):
    circunferencia = 2 * 3.1416 * radio
    return circunferencia

# 3. Zona de salida
def mostrar_resultado(valor_final):
    print("La circunferencia del circulo es:",valor_final)

# ZONA PRINCIPAL
radio_circulo = tomar_radio()
resultado = calcular_circunferencia(radio_circulo)
mostrar_resultado(resultado)

#31. Desarrolla un programa que pida un número de horas y lo convierta a minutos utilizando operadores aritméticos.

#zona entrada
def tomar_horas():
    horas = int(input("Escribe la cantidad de horas: "))
    return horas

#zona proceso de datos
def calcular_minutos(horas):
    minutos = horas * 60
    return minutos

#zona salida
def mostrar_resultado(valor_final):
    print("El resultado en minutos es:",valor_final)

#zona principal

ho=tomar_horas()
resultado=calcular_minutos(ho)
mostrar_resultado(resultado)

#32. Diseña un algoritmo que calcule el área de un rectángulo, solicitando su longitud y ancho.

#zona entrada
def tomar_longitud():
    longitud = float(input("Escribe la longitud: "))
    return longitud

def tomar_ancho():
    ancho = float(input("Escribe el ancho: "))
    return ancho

#zona proceso
def calcular_area(l, a):
    area = l * a
    return area

#zona salida

def mostrar_resultado(valor_final):
    print("El área del rectángulo es:",valor_final)

#zona principal

lon=tomar_longitud()
an=tomar_ancho()
resultado=calcular_area(lon,an)
mostrar_resultado(resultado)

#33. Crea un algoritmo que solicite una distancia en kilómetros y la convierta a millas.

#zona tomar datos
def tomar_dato():
  km=int(input("Escriba los kilometros:"))
  return km

#zona procesar
def calcular_millas(kilom):
  millas=kilom * 0.621371
  return millas

#zona salida
def mostrar_dato(resultado):
  print("las millas son", resultado)

#zona principal

kilometros=tomar_dato()
res=calcular_millas(kilometros)
mostrar_dato(res)

#34.Desarrolla un programa que pida el precio de un artículo y calcule el 10% de descuento.

#zona de tomar datos
def tomar_precio():
  precio=float(input("Escriba el precio:"))
  return precio

#zona de procesar
def calcular_descuento(pr):
  desc=pr*0.10
  return desc

#zona de salida
def mostrar_dato(r):
  print("el 10% de descuento es:",r)

#zona principal
p=tomar_precio()
rta=calcular_descuento(p)
mostrar_dato(rta)

#35.Diseña un algoritmo que solicite la cantidad de dinero en una cuenta y calcule el 5% de interés.

#zona tomar dato
def tomar_cuenta():
  dinero=float(input("Escriba la cantidad de dinero:"))
  return dinero

#zona de procesar
def calcular_int(d):
  interes=d*0.05
  return interes

#zona de salida
def mostrar_dato(res):
 print("el 5% del interes es",res)

#zona principal
dine=tomar_cuenta()
r=calcular_int(dine)
mostrar_dato(r)

#36 Escribe un programa que pida dos números enteros y muestre el cociente de la división entera.

#zona tomar dato
def tomar_numero1():
  numero1=int(input("Escriba el primer numero: "))
  return numero1

def tomar_numero2():
  numero2=int(input("Escriba el segundo numero: "))
  return numero2

#zona proceso
def calcular_coc(n1,n2):
  resul= n1//n2
  return resul

#zona salida
def mostrar_dato(resul):
  print("El cociente es:", resul)

#zona principal
num1=tomar_numero1()
num2=tomar_numero2()
r=calcular_coc(num1,num2)
mostrar_dato(r)

#37 Crea un algoritmo que determine si un número es múltiplo de otro ingresados por el usuario.

#zona tomar dato
def tomar_numero1():
  numero1=int(input("Escriba el primer numero: "))
  return numero1

def tomar_numero2():
  numero2=int(input("Escriba el segundo numero: "))
  return numero2

#zona proceso
def calcular_multiplo(num1, num2):
  resultado=num1 % num2
  return resultado

#zona salida
def mostrar_dato(r):
  if r==0:
    print("es multiplo ")
  else:
    print("no es multiplo ")

#zona principal

n1=tomar_numero1()
n2=tomar_numero2()
res=calcular_multiplo(n1,n2)
mostrar_dato(res)

#38. Desarrolla un programa que pida dos números y muestre el mayor de los dos utilizando operadores aritméticos.
#zona tomar dato
def tomar_numero1():
  numero1=int(input("Escriba el primer numero: "))
  return numero1

def tomar_numero2():
  numero2=int(input("Escriba el segundo numero: "))
  return numero2
#zona proceso

def calcular_mayor(n1,n2):
  if n1 > n2:
    mayor =  n1
  else:
    mayor= n2
  return mayor

#zona salidad
def mostrar_dato(mayor):
  print("El número mayor es:", mayor)

#zona principal
n1=tomar_numero1()
n2=tomar_numero2()
resultado = calcular_mayor(n1, n2)
mostrar_dato(resultado)

#39. Diseña un algoritmo que solicite dos números y calcule el promedio de ambos

# Función para tomar el primer número
def tomar_numero1():
    numero1 = float(input("Escribe el primer número: "))
    return numero1

# Función para tomar el segundo número
def tomar_numero2():
    numero2 = float(input("Escribe el segundo número: "))
    return numero2

# Función para calcular el promedio
def calcular_promedio(n1, n2):
    promedio = (n1 + n2) / 2
    return promedio

# Función para mostrar el resultado
def mostrar_resultado(promedio):
    print("El promedio de los dos números es:", promedio)

# Zona principal
num1 = tomar_numero1()
num2 = tomar_numero2()
resultado = calcular_promedio(num1, num2)
mostrar_resultado(resultado)